# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # Add an empty line to all file
      - id: end-of-file-fixer
      - id: mixed-line-ending
        exclude: ^.git/
        args:
          - "--fix=crlf"

      # Trims trailing whitespace
      - id: trailing-whitespace

      # Ensure that links to code on GitHub use the permalinks
      - id: check-vcs-permalinks

      # Syntax validation
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml

      # JSON auto-formatter
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=2"
          - "--no-sort-keys"

      # Checks for git-related issues
      - id: check-case-conflict
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1.3.0
    hooks:
      - id: conventional-pre-commit
        name: Check commit msg
        stages: [commit-msg]

  - repo: https://github.com/python-poetry/poetry
    rev: '1.5.0'  # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        name: "export requirements"
        args: ["-f", "requirements.txt", "-o", "requirements/requirements.txt"]
      - id: poetry-export
        name: "export dev requirements"
        args: ["-f", "requirements.txt", "--with", "dev", "-o", "requirements/requirements-dev.txt"]
      - id: poetry-export
        name: "export docs requirements"
        args: ["-f", "requirements.txt", "--with", "docs", "-o", "requirements/requirements-docs.txt"]
