version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3"

python:
  install:
    - method: pip
      path: .
      requirements: requirements/requirements-docs.txt

formats:
  - pdf
  - epub
  - htmlzip
