[tool.poetry]
name = "Fabricius"
version = "0.2.0dev2"
description = "Fabricius: The supportive templating engine for Python!"
license = "MIT"
authors = ["Predeactor <pro.julien.mauroy@gmail.com>"]
readme = "README.md"
repository = "https://github.com/Predeactor/Fabricius"
documentation = "https://fabricius.readthedocs.org"
keywords = ["cookiecutter", "template", "project", "scaffold", "pyscaffold"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",

    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",

    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",

    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: Implementation :: CPython",
    "Operating System :: OS Independent",

    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Build Tools",
    "Topic :: Utilities",

    "Typing :: Typed",
]

packages = [
    { include = "fabricius" }
]

include = ["README.md", "LICENSE"]

[tool.poetry.dependencies]
python = "^3.10"
chevron = "^0.14.0"
rich = "^12.4.4"
typing-extensions = "^4.2.0"
inflection = "^0.5.1"
click = "^8.1.3"
jinja2 = "^3.1.2"
jinja2-time = "^0.2.0"
slugify = "^0.0.1"
pyyaml = "^6.0"

# Extra: Docs
Sphinx = { version = "^5.0.2", optional = true }
furo = { version = "^2022.6.21", optional = true }
sphinx-autobuild = { version = "^2021.3.14", optional = true }

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
isort = "^5.12.0"
pre-commit = "^2.19.0"
mypy = "^1.0.0"
tox = "^4.4.5"
types-chevron = "^0.14.2.2"
esbonio = "^0.16.1"
ipykernel = "^6.22.0"
pytest = "^7.3.1"
poethepoet = "^0.20.0"

[tool.poetry.group.actions]
optional = true

[tool.poetry.group.actions.dependencies]
tox-gh-actions = "^3.0.0"

[tool.poetry.extras]
docs = ["Sphinx", "sphinx-autobuild", "furo"]

[tool.poe]
poetry_command = ""

[tool.poe.tasks]
_format_black = "black ."
_format_isort = "isort ."
format = ["_format_black", "_format_isort"]
test = "pytest . -v"

[tool.poe.tasks.docs]
cmd = "make livehtml"
cwd = "./docs"

[tool.poe.tasks.docscov]
cmd = "make html -b coverage"
cwd = "./docs"

[tool.black]
line-length = 99

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
