[tool.poetry]
name = "Fabricius"
version = "0.0.2"
description = "Fabricius: The supportive templating engine for Python!"
license = "MIT"
authors = ["Predeactor <pro.julien.mauroy@gmail.com>"]
readme = "README.md"
repository = "https://github.com/Predeactor/Fabricius"
documentation = "https://fabricius.readthedocs.org"
keywords = ["cookiecutter", "template", "project", "scaffold", "pyscaffold"]
classifiers = [
    "Development Status :: 1 - Planning",

    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",

    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",

    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: Implementation :: CPython",
    "Operating System :: OS Independent",

    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Build Tools",
    "Topic :: Utilities",

    "Typing :: Typed",
]

packages = [
    { include = "fabricius" }
]

include = ["README.md", "LICENSE"]

[tool.poetry.dependencies]
python = "^3.10"
chevron = "^0.14.0"
rich = "^12.4.4"
typing-extensions = "^4.2.0"
inflection = "^0.5.1"

# Extra: Docs
Sphinx = { version = "^5.0.2", optional = true }
furo = { version = "^2022.6.21", optional = true }
sphinx-autobuild = { version = "^2021.3.14", optional = true }

[tool.poetry.dev-dependencies]
black = "^22.3.0"
isort = "^5.10.1"
pre-commit = "^2.19.0"
mypy = "^0.961"
tox = "^3.25.1"
tox-gh-actions = "^2.9.1"

[tool.poetry.extras]
docs = ["Sphinx", "sphinx-autobuild", "furo"]

[tool.black]
line_length = 99

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
