from git.cmd import Git
from git.types import PathLike
from gitdb.base import OInfo, OStream
from gitdb.db import GitDB as GitDB
from gitdb.db import LooseObjectDB

class GitCmdObjectDB(LooseObjectDB):
    def __init__(self, root_path: PathLike, git: Git) -> None: ...
    def info(self, binsha: bytes) -> OInfo: ...
    def stream(self, binsha: bytes) -> OStream: ...
    def partial_to_complete_sha_hex(self, partial_hexsha: str) -> bytes: ...
