name: Fabricius Tests
on:
  pull_request:
    types: [opened, ready_for_review]
  push:

jobs:
  test:
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        python-version: ['3.12']

    runs-on: ${{ matrix.os }}
    name: Tests on ${{ matrix.os }} using py${{ matrix.python-version }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Load cached Poetry installation
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-${{ matrix.os }}-0 # To reset cache, increment

      - name: Install Poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          install-parallel: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - run: |
          source .venv/scripts/activate
        if: runner.os == 'Windows'
      - run: |
          source .venv/bin/activate
        if: runner.os != 'Windows'

      - name: Install package
        run: poetry install --with dev,actions

      # - name: Run linting
      #   run: poetry run poe lint

      - name: Run Tox
        run: poetry run tox
