name: Fabricius Tests
on:
  pull_request:
    types: [opened, ready_for_review]
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.12']

    runs-on: ${{ matrix.os }}
    name: Tests on ${{ matrix.os }} using py${{ matrix.python-version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }} & PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
          cache-dependency-path: |
            pdm.lock
            pyproject.toml
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: pdm install --dev

      # - name: Run linting
      #   run: pdm run lint

      - name: Run Tox
        run: tox

      - name : Upload test report
        if: ${{ ! cancelled() }}
        uses: actions/upload-artifact@v3
        with:
          name: tests-report-${{ matrix.os }}-py${{ matrix.python-version }}
          path: ./tests/report/
